export enum StatusItem{
    TROCA_SOLICITADA = "TROCA_SOLICITADA",
    TROCA_EM_ANALISE = "TROCA_EM_ANALISE",
    TROCA_APROVADA = "TROCA_APROVADA",
    TROCA_REALIZADA = "TROCA_REALIZADA",
    TROCA_NEGADA = "TROCA_NEGADA"
}
